# Generated by Django 5.1.7 on 2025-03-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('part_of_speech', models.CharField(choices=[('N', 'Noun'), ('V', 'Verb'), ('Adj', 'Adjective')], default='N', max_length=3)),
            ],
        ),
    ]
