# Generated by Django 5.1.7 on 2025-03-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='part_of_speech',
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
