# Generated by Django 5.1.7 on 2025-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_word_part_of_speech_word_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='conjugation',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='gender',
            field=models.CharField(blank=True, choices=[('N', 'Noun'), ('V', 'Verb'), ('Adj', 'Adjective'), ('Adv', 'Adverb'), ('Exp', 'Expression')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('N', 'Noun'), ('V', 'Verb'), ('Adj', 'Adjective'), ('Adv', 'Adverb'), ('Exp', 'Expression')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
