# Generated by Django 5.1.7 on 2025-03-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_word_conjugation_word_gender_word_part_of_speech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_id',
            new_name='id',
        ),
    ]
