# Generated by Django 5.1.7 on 2025-03-11 15:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_word_id_word_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='required_case',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('N', 'Nominative'), ('G', 'Genitive'), ('D', 'Dative'), ('Ac', 'Accusative'), ('Instr', 'Instrumental'), ('Loc', 'Locative'), ('V', 'Vocative')], max_length=10, null=True),
        ),
    ]
