# Generated by Django 5.1.7 on 2025-03-11 15:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_word_required_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='word',
            name='required_case',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nom', 'Nominative'), ('Gen', 'Genitive'), ('Dat', 'Dative'), ('Acc', 'Accusative'), ('Instr', 'Instrumental'), ('Loc', 'Locative'), ('Voc', 'Vocative')], max_length=10, null=True),
        ),
    ]
