# Generated by Django 5.1.7 on 2025-03-11 15:21

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_word_options_alter_word_required_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='required_case',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Nom', 'Nominative'), ('Gen', 'Genitive'), ('Dat', 'Dative'), ('Acc', 'Accusative'), ('Instr', 'Instrumental'), ('Loc', 'Locative'), ('Voc', 'Vocative')], max_length=100, null=True),
        ),
    ]
