# Generated by Django 5.1.7 on 2025-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_word_required_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='number',
            field=models.CharField(choices=[('SG', 'Singular'), ('PL', 'Plural')], default='SG', max_length=10),
        ),
    ]
