# Generated by Django 4.2.20 on 2025-03-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_word_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='name',
        ),
    ]
