# Generated by Django 4.2.20 on 2025-03-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_word_word_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'Neuter')], max_length=10, null=True),
        ),
    ]
