# Generated by Django 4.2.20 on 2025-03-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_word_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='required_case',
            new_name='required_cases',
        ),
        migrations.RemoveField(
            model_name='word',
            name='conjugation',
        ),
        migrations.RemoveField(
            model_name='word',
            name='gender',
        ),
        migrations.AddField(
            model_name='word',
            name='plural',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='verb_class',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('IRR', 'Irregular')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='number',
            field=models.CharField(choices=[('SG', 'Singular'), ('PL', 'Plural')], max_length=10),
        ),
    ]
