# Generated by Django 4.2.20 on 2025-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_required_case_word_required_cases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='plural',
        ),
        migrations.AddField(
            model_name='word',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'Neuter')], max_length=200, null=True),
        ),
    ]
