# Generated by Django 4.2.20 on 2025-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_word_plural_word_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='number',
            field=models.CharField(blank=True, choices=[('SG', 'Singular'), ('PL', 'Plural')], max_length=10, null=True),
        ),
    ]
