# Generated by Django 4.2.20 on 2025-03-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_word_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Feminine'), ('N', 'Neuter'), ('V', 'Virile'), ('NV', 'Non-virile')], max_length=200, null=True),
        ),
    ]
